<a href="https://colab.research.google.com/github/infotovikas/Learn-Python/blob/main/intermediate/Basic_Operations_with_Dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#### Basic Operations with Dataframes

In [2]:
import pandas as pd

stats = pd.read_csv('/content/sample_data/SampleData.csv')

In [3]:
stats.head()

,Age,Gender,Occupation,Income (USD),Location,Marital Status,Education Level
0,25,Male,Employed,"50,000",New York,Single,Bachelors
1,34,Female,Student,"20,000",Los Angeles,Single,High School
2,55,Male,Retired,"40,000",Chicago,Married,Masters
3,28,Female,Employed,"60,000",San Francisco,Married,Bachelors
4,42,Other,Self-employed,"1,00,000",Miami,Divorced,PhD

In [6]:
stats.columns

Index(['Age', 'Gender', 'Occupation', 'Income (USD)', 'Location',
       'Marital Status', 'Education Level'],
      dtype='object')

In [19]:
#stats.describe()
stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             11 non-null     int64
 1   Gender          11 non-null     object
 2   Occupation      11 non-null     object
 3   Income_USD      11 non-null     object
 4   Location        11 non-null     object
 5   MaritalStatus   11 non-null     object
 6   EducationLevel  11 non-null     object
dtypes: int64(1), object(6)
memory usage: 748.0+ bytes

In [ ]:
# Convert the column from object to int64
stats['Income_USD'] = stats['Income_USD'].astype('int64') # this will give you error if there is ',' comma in column values so use below one.

In [21]:
# Remove commas and convert the column to integer
stats['Income_USD'] = stats['Income_USD'].replace({',': ''}, regex=True).astype('int64')

In [12]:
stats.columns = ['Age', 'Gender', 'Occupation', 'Income_USD', 'Location', 'MaritalStatus', 'EducationLevel']

In [10]:
## Subsetting few columns from above dataframe-
stats[['Age', 'Gender', 'Occupation']] [4:8]

   Age  Gender     Occupation
4   42   Other  Self-employed
5   38    Male       Employed
6   67  Female        Retired
7   23    Male        Student

In [22]:
## Mathematical Operatoins-
result = stats.Age * stats.Income_USD
result.head()

0    1250000
1     680000
2    2200000
3    1680000
4    4200000
dtype: int64

In [25]:
## Add Column into Dataframe-
stats['MyCalc'] = stats.Age * stats.Income_USD
stats

,Age,Gender,Occupation,Income_USD,Location,MaritalStatus,EducationLevel,MyCalc
0,25,Male,Employed,50000,New York,Single,Bachelors,1250000
1,34,Female,Student,20000,Los Angeles,Single,High School,680000
2,55,Male,Retired,40000,Chicago,Married,Masters,2200000
3,28,Female,Employed,60000,San Francisco,Married,Bachelors,1680000
4,42,Other,Self-employed,100000,Miami,Divorced,PhD,4200000
5,38,Male,Employed,75000,Houston,Single,Bachelors,2850000
6,67,Female,Retired,30000,Phoenix,Widowed,High School,2010000
7,23,Male,Student,15000,Denver,Single,High School,345000
8,48,Female,Employed,85000,Boston,Married,Masters,4080000
9,31,Male,Self-employed,55000,Seattle,Married,Bachelors,1705000
10,37,Male,Self-employed,65000,Texas,Married,Masters,2405000

In [27]:
## Comparison to R
stats['PQR'] = [1, 2, 3, 4, 5] # Error as Python has no recycling option.

In [ ]:
## Removing a column

In [28]:
stats.head()

,Age,Gender,Occupation,Income_USD,Location,MaritalStatus,EducationLevel,MyCalc
0,25,Male,Employed,50000,New York,Single,Bachelors,1250000
1,34,Female,Student,20000,Los Angeles,Single,High School,680000
2,55,Male,Retired,40000,Chicago,Married,Masters,2200000
3,28,Female,Employed,60000,San Francisco,Married,Bachelors,1680000
4,42,Other,Self-employed,100000,Miami,Divorced,PhD,4200000

**Explanation:**
1. 'MyCalc': This is the column you want to drop.
2. axis=1: This indicates that you want to drop a column. (If you want to drop rows, you'd use axis=0).
3. inplace=True: This will modify the DataFrame in place, meaning it will directly update stats. If you want to return a new DataFrame without modifying the original, you can remove inplace=True.

In [33]:
#stats.drop('MyCalc', axis=1, inplace=True)
stats.drop('MyCalc', axis=1)

,Age,Gender,Occupation,Income_USD,Location,MaritalStatus,EducationLevel
0,25,Male,Employed,50000,New York,Single,Bachelors
1,34,Female,Student,20000,Los Angeles,Single,High School
2,55,Male,Retired,40000,Chicago,Married,Masters
3,28,Female,Employed,60000,San Francisco,Married,Bachelors
4,42,Other,Self-employed,100000,Miami,Divorced,PhD
5,38,Male,Employed,75000,Houston,Single,Bachelors
6,67,Female,Retired,30000,Phoenix,Widowed,High School
7,23,Male,Student,15000,Denver,Single,High School
8,48,Female,Employed,85000,Boston,Married,Masters
9,31,Male,Self-employed,55000,Seattle,Married,Bachelors
10,37,Male,Self-employed,65000,Texas,Married,Masters

In [34]:
stats.head()

,Age,Gender,Occupation,Income_USD,Location,MaritalStatus,EducationLevel,MyCalc
0,25,Male,Employed,50000,New York,Single,Bachelors,1250000
1,34,Female,Student,20000,Los Angeles,Single,High School,680000
2,55,Male,Retired,40000,Chicago,Married,Masters,2200000
3,28,Female,Employed,60000,San Francisco,Married,Bachelors,1680000
4,42,Other,Self-employed,100000,Miami,Divorced,PhD,4200000

In [35]:
stats.drop('MyCalc', axis=1, inplace=True)

In [36]:
stats.head()

,Age,Gender,Occupation,Income_USD,Location,MaritalStatus,EducationLevel
0,25,Male,Employed,50000,New York,Single,Bachelors
1,34,Female,Student,20000,Los Angeles,Single,High School
2,55,Male,Retired,40000,Chicago,Married,Masters
3,28,Female,Employed,60000,San Francisco,Married,Bachelors
4,42,Other,Self-employed,100000,Miami,Divorced,PhD

In [ ]:
### Filtering Data Frames

In [ ]:
## Filtering is about Rows

In [37]:
stats.head()

,Age,Gender,Occupation,Income_USD,Location,MaritalStatus,EducationLevel
0,25,Male,Employed,50000,New York,Single,Bachelors
1,34,Female,Student,20000,Los Angeles,Single,High School
2,55,Male,Retired,40000,Chicago,Married,Masters
3,28,Female,Employed,60000,San Francisco,Married,Bachelors
4,42,Other,Self-employed,100000,Miami,Divorced,PhD

In [39]:
stats.Age < 28

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10    False
Name: Age, dtype: bool

In [40]:
Filter = stats.Age < 28

In [41]:
stats[3:9]

,Age,Gender,Occupation,Income_USD,Location,MaritalStatus,EducationLevel
3,28,Female,Employed,60000,San Francisco,Married,Bachelors
4,42,Other,Self-employed,100000,Miami,Divorced,PhD
5,38,Male,Employed,75000,Houston,Single,Bachelors
6,67,Female,Retired,30000,Phoenix,Widowed,High School
7,23,Male,Student,15000,Denver,Single,High School
8,48,Female,Employed,85000,Boston,Married,Masters

In [42]:
stats[Filter] # Conceptually this is just like R

   Age Gender Occupation  Income_USD  Location MaritalStatus EducationLevel
0   25   Male   Employed       50000  New York        Single      Bachelors
7   23   Male    Student       15000    Denver        Single    High School

In [ ]:
#Awesome! Lets use this in practice now.

In [47]:
stats[stats.Age < 28 and stats['Income_USD'] < 40000] # this will work in R. However, in Python we can use & in place of 'and' logical operator.

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [51]:
stats[(stats.Age < 28) & (stats['Income_USD'] < 40000)]

   Age Gender Occupation  Income_USD Location MaritalStatus EducationLevel
7   23   Male    Student       15000   Denver        Single    High School

In [52]:
stats.head()

,Age,Gender,Occupation,Income_USD,Location,MaritalStatus,EducationLevel
0,25,Male,Employed,50000,New York,Single,Bachelors
1,34,Female,Student,20000,Los Angeles,Single,High School
2,55,Male,Retired,40000,Chicago,Married,Masters
3,28,Female,Employed,60000,San Francisco,Married,Bachelors
4,42,Other,Self-employed,100000,Miami,Divorced,PhD

In [54]:
stats[stats.EducationLevel == 'High School']

,Age,Gender,Occupation,Income_USD,Location,MaritalStatus,EducationLevel
1,34,Female,Student,20000,Los Angeles,Single,High School
6,67,Female,Retired,30000,Phoenix,Widowed,High School
7,23,Male,Student,15000,Denver,Single,High School

In [ ]:
### How to get the unique category-

In [55]:
stats.EducationLevel.unique()

array(['Bachelors', 'High School', 'Masters', 'PhD'], dtype=object)

In [ ]:
## Find out everything about Malta

In [56]:
stats[stats.Location == 'Phoenix']

   Age  Gender Occupation  Income_USD Location MaritalStatus EducationLevel
6   67  Female    Retired       30000  Phoenix       Widowed    High School