<a href="https://colab.research.google.com/github/infotovikas/Learn-Python/blob/main/intermediate/Dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
# Method 1: Specify Full Path To File

In [ ]:
#Windows:
stats = pd.read_csv('/content/sample_data/SampleData.csv')

In [ ]:
#1. Full Dataframe
stats

,Age,Gender,Occupation,Income (USD),Location,Marital Status,Education Level
0,25,Male,Employed,"50,000",New York,Single,Bachelors
1,34,Female,Student,"20,000",Los Angeles,Single,High School
2,55,Male,Retired,"40,000",Chicago,Married,Masters
3,28,Female,Employed,"60,000",San Francisco,Married,Bachelors
4,42,Other,Self-employed,"1,00,000",Miami,Divorced,PhD
5,38,Male,Employed,"75,000",Houston,Single,Bachelors
6,67,Female,Retired,"30,000",Phoenix,Widowed,High School
7,23,Male,Student,"15,000",Denver,Single,High School
8,48,Female,Employed,"85,000",Boston,Married,Masters
9,31,Male,Self-employed,"55,000",Seattle,Married,Bachelors
10,37,Male,Self-employed,"65,000",Texas,Married,Masters

In [ ]:
# Method 2: Change Working Directory

In [ ]:
import os

In [ ]:
print(os.getcwd())
#os.chdir('c:\\Learning\\python\\sampledata.csv')

/content

In [ ]:
### Exploring the Data

In [ ]:
#2. No of Rows
len(stats)

11

In [ ]:
#3. See Columns
stats.columns

Index(['Age', 'Gender', 'Occupation', 'Income (USD)', 'Location',
       'Marital Status', 'Education Level'],
      dtype='object')

In [ ]:
#4. No of Columns
len(stats.columns)

7

In [ ]:
#5. Top Rows
stats.head(6)   # remember the brackets

,Age,Gender,Occupation,Income (USD),Location,Marital Status,Education Level
0,25,Male,Employed,"50,000",New York,Single,Bachelors
1,34,Female,Student,"20,000",Los Angeles,Single,High School
2,55,Male,Retired,"40,000",Chicago,Married,Masters
3,28,Female,Employed,"60,000",San Francisco,Married,Bachelors
4,42,Other,Self-employed,"1,00,000",Miami,Divorced,PhD
5,38,Male,Employed,"75,000",Houston,Single,Bachelors

In [ ]:
#6. Bottom Rows
stats.tail(2)   # remember the brackets

,Age,Gender,Occupation,Income (USD),Location,Marital Status,Education Level
9,31,Male,Self-employed,"55,000",Seattle,Married,Bachelors
10,37,Male,Self-employed,"65,000",Texas,Married,Masters

In [ ]:
#7. Information on the columns
stats.info()  #like the str() function in R

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              11 non-null     int64
 1   Gender           11 non-null     object
 2   Occupation       11 non-null     object
 3   Income (USD)     11 non-null     object
 4   Location         11 non-null     object
 5   Marital Status   11 non-null     object
 6   Education Level  11 non-null     object
dtypes: int64(1), object(6)
memory usage: 748.0+ bytes

In [ ]:
#8. Get stats on the columns
stats.describe() #like summary() function in R

             Age
count  11.000000
mean   38.909091
std    13.404884
min    23.000000
25%    29.500000
50%    37.000000
75%    45.000000
max    67.000000

In [31]:
#The above can more readable using Transpose() function
stats.describe().transpose()

     count       mean        std   min   25%   50%   75%   max
Age   11.0  38.909091  13.404884  23.0  29.5  37.0  45.0  67.0

In [ ]:
### Renaming of the Columns in Dataframe

In [32]:
stats.head(1)

   Age Gender Occupation Income (USD)  Location Marital Status Education Level
0   25   Male   Employed       50,000  New York         Single       Bachelors

In [33]:
stats.columns

Index(['Age', 'Gender', 'Occupation', 'Income (USD)', 'Location',
       'Marital Status', 'Education Level'],
      dtype='object')

In [34]:
stats.columns = ['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [36]:
stats.head(1)

    a     b         c       d         e       f          g
0  25  Male  Employed  50,000  New York  Single  Bachelors

In [38]:
stats.columns = ['Age', 'Gender', 'Occupation', 'Income(USD)', 'Location',
       'MaritalStatus', 'EducationLevel']

In [39]:
stats.head(2)

,Age,Gender,Occupation,Income(USD),Location,MaritalStatus,EducationLevel
0,25,Male,Employed,"50,000",New York,Single,Bachelors
1,34,Female,Student,"20,000",Los Angeles,Single,High School