<a href="https://colab.research.google.com/github/infotovikas/Learn-Python/blob/main/intermediate/Subsetting_Dataframes_in_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#### Subsetting Dataframes in Pandas

In [3]:
import pandas as pd

stats = pd.read_csv('/content/sample_data/SampleData.csv')

In [4]:
stats.head()

,Age,Gender,Occupation,Income (USD),Location,Marital Status,Education Level
0,25,Male,Employed,"50,000",New York,Single,Bachelors
1,34,Female,Student,"20,000",Los Angeles,Single,High School
2,55,Male,Retired,"40,000",Chicago,Married,Masters
3,28,Female,Employed,"60,000",San Francisco,Married,Bachelors
4,42,Other,Self-employed,"1,00,000",Miami,Divorced,PhD

In [ ]:
#Three parts will cover-
# -Rows
# -Columns
#-Combine the above two

In [5]:
#Part1. -Rows
stats[2:4]   # slicing the dataframe and getting row from 2 to 4 as its indexing start from 0 so 4th row will be exluded

,Age,Gender,Occupation,Income (USD),Location,Marital Status,Education Level
2,55,Male,Retired,"40,000",Chicago,Married,Masters
3,28,Female,Employed,"60,000",San Francisco,Married,Bachelors

In [6]:
stats[:] #get everything in stats - all the rows

,Age,Gender,Occupation,Income (USD),Location,Marital Status,Education Level
0,25,Male,Employed,"50,000",New York,Single,Bachelors
1,34,Female,Student,"20,000",Los Angeles,Single,High School
2,55,Male,Retired,"40,000",Chicago,Married,Masters
3,28,Female,Employed,"60,000",San Francisco,Married,Bachelors
4,42,Other,Self-employed,"1,00,000",Miami,Divorced,PhD
5,38,Male,Employed,"75,000",Houston,Single,Bachelors
6,67,Female,Retired,"30,000",Phoenix,Widowed,High School
7,23,Male,Student,"15,000",Denver,Single,High School
8,48,Female,Employed,"85,000",Boston,Married,Masters
9,31,Male,Self-employed,"55,000",Seattle,Married,Bachelors
10,37,Male,Self-employed,"65,000",Texas,Married,Masters

In [7]:
stats[3:] # start from 3rd to end

,Age,Gender,Occupation,Income (USD),Location,Marital Status,Education Level
3,28,Female,Employed,"60,000",San Francisco,Married,Bachelors
4,42,Other,Self-employed,"1,00,000",Miami,Divorced,PhD
5,38,Male,Employed,"75,000",Houston,Single,Bachelors
6,67,Female,Retired,"30,000",Phoenix,Widowed,High School
7,23,Male,Student,"15,000",Denver,Single,High School
8,48,Female,Employed,"85,000",Boston,Married,Masters
9,31,Male,Self-employed,"55,000",Seattle,Married,Bachelors
10,37,Male,Self-employed,"65,000",Texas,Married,Masters

In [8]:
stats[:7]  # starts from begining till 7th like top 7 (stats.head(7))

,Age,Gender,Occupation,Income (USD),Location,Marital Status,Education Level
0,25,Male,Employed,"50,000",New York,Single,Bachelors
1,34,Female,Student,"20,000",Los Angeles,Single,High School
2,55,Male,Retired,"40,000",Chicago,Married,Masters
3,28,Female,Employed,"60,000",San Francisco,Married,Bachelors
4,42,Other,Self-employed,"1,00,000",Miami,Divorced,PhD
5,38,Male,Employed,"75,000",Houston,Single,Bachelors
6,67,Female,Retired,"30,000",Phoenix,Widowed,High School

In [11]:
## Reverse the dataframe
stats[ : : -1] # (start from begining, till end, step out -1)

,Age,Gender,Occupation,Income (USD),Location,Marital Status,Education Level
10,37,Male,Self-employed,"65,000",Texas,Married,Masters
9,31,Male,Self-employed,"55,000",Seattle,Married,Bachelors
8,48,Female,Employed,"85,000",Boston,Married,Masters
7,23,Male,Student,"15,000",Denver,Single,High School
6,67,Female,Retired,"30,000",Phoenix,Widowed,High School
5,38,Male,Employed,"75,000",Houston,Single,Bachelors
4,42,Other,Self-employed,"1,00,000",Miami,Divorced,PhD
3,28,Female,Employed,"60,000",San Francisco,Married,Bachelors
2,55,Male,Retired,"40,000",Chicago,Married,Masters
1,34,Female,Student,"20,000",Los Angeles,Single,High School
0,25,Male,Employed,"50,000",New York,Single,Bachelors

In [10]:
## Gen only every 3rd rows
stats[::-3]

,Age,Gender,Occupation,Income (USD),Location,Marital Status,Education Level
10,37,Male,Self-employed,"65,000",Texas,Married,Masters
7,23,Male,Student,"15,000",Denver,Single,High School
4,42,Other,Self-employed,"1,00,000",Miami,Divorced,PhD
1,34,Female,Student,"20,000",Los Angeles,Single,High School

In [12]:
#Part2. -Columns
stats.columns

Index(['Age', 'Gender', 'Occupation', 'Income (USD)', 'Location',
       'Marital Status', 'Education Level'],
      dtype='object')

In [13]:
stats.head()

,Age,Gender,Occupation,Income (USD),Location,Marital Status,Education Level
0,25,Male,Employed,"50,000",New York,Single,Bachelors
1,34,Female,Student,"20,000",Los Angeles,Single,High School
2,55,Male,Retired,"40,000",Chicago,Married,Masters
3,28,Female,Employed,"60,000",San Francisco,Married,Bachelors
4,42,Other,Self-employed,"1,00,000",Miami,Divorced,PhD

In [14]:
stats['Location']  # Get the Location column only from the dataframe

0          New York
1       Los Angeles
2           Chicago
3     San Francisco
4             Miami
5           Houston
6           Phoenix
7            Denver
8            Boston
9           Seattle
10            Texas
Name: Location, dtype: object

In [15]:
stats['Location'].head()

0         New York
1      Los Angeles
2          Chicago
3    San Francisco
4            Miami
Name: Location, dtype: object

In [18]:
###Get two columns from the dataframes
#stats['Location', 'Marital Status'].head()  # this will give an error so you need to pass multiple column as list into squre brackets
stats[['Location', 'Marital Status']].head()

        Location Marital Status
0       New York         Single
1    Los Angeles         Single
2        Chicago        Married
3  San Francisco        Married
4          Miami       Divorced

In [16]:
['Location', 'Marital Status']

['Location', 'Marital Status']

In [19]:
#Quck Access - requires the name to be one word
stats.head()

,Age,Gender,Occupation,Income (USD),Location,Marital Status,Education Level
0,25,Male,Employed,"50,000",New York,Single,Bachelors
1,34,Female,Student,"20,000",Los Angeles,Single,High School
2,55,Male,Retired,"40,000",Chicago,Married,Masters
3,28,Female,Employed,"60,000",San Francisco,Married,Bachelors
4,42,Other,Self-employed,"1,00,000",Miami,Divorced,PhD

In [20]:
stats.Occupation.head() # this is the quick access

0         Employed
1          Student
2          Retired
3         Employed
4    Self-employed
Name: Occupation, dtype: object

In [22]:
#Part3. Combining the Rows and Column

In [23]:
stats[2:4][['Location', 'Marital Status']]

        Location Marital Status
2        Chicago        Married
3  San Francisco        Married

In [24]:
stats[['Location', 'Marital Status']][2:4]

        Location Marital Status
2        Chicago        Married
3  San Francisco        Married